#!/usr/bin/env node
/* eslint-disable no-console */

const fs = require("fs");
const path = require("path");
const { spawnSync } = require("child_process");

const ROOT = path.resolve(__dirname, "..");
const EVIDENCE_ENV = path.join(ROOT, "..", "hk-criminal-procedure-graphrag-evidence", ".env.local");
const VERCEL_PRODUCTION_ENV = path.join(ROOT, ".env.vercel.production");
const TARGET_ENV = path.join(ROOT, ".env.local");

const {
  defaultFreeOpenRouterChatModel,
  defaultFreeOpenRouterEmbeddingDim,
  defaultFreeOpenRouterEmbeddingModel,
  defaultFreeOpenRouterRerankModel,
} = require("../src/retrieval/openrouter_free_models");

const PRODUCTION_OVERRIDES_BASE = {
  LEGAL_RUNTIME_MODE: "production_scale",
  OPENROUTER_FREE_ONLY: "true",
  OPENROUTER_ALLOW_PAID: "false",
  OPENROUTER_MODEL: defaultFreeOpenRouterChatModel(),
  INNGEST_DEV: "1",
  LEGAL_QDRANT_NAMESPACE_AUTO: "true",
  LEGAL_OPENROUTER_ALLOWED_KEY_SUFFIX: "11bb60",
  QDRANT_COLLECTION_PARAGRAPHS: "hk_legal_paragraphs_prod",
  QDRANT_COLLECTION_PROPOSITIONS: "hk_proposition_cards_prod",
  PUBLIC_DEMO_MODE: "true",
  PRIVATE_SOURCE_INGESTION_ENABLED: "false",
};

function productionOverrides(merged = {}) {
  if (merged.OPENROUTER_API_KEY) {
    return {
      ...PRODUCTION_OVERRIDES_BASE,
      LEGAL_EMBEDDING_PROVIDER: "openrouter",
      LEGAL_EMBEDDING_MODEL: merged.LEGAL_EMBEDDING_MODEL || defaultFreeOpenRouterEmbeddingModel(),
      LEGAL_EMBEDDING_DIM: merged.LEGAL_EMBEDDING_DIM || String(defaultFreeOpenRouterEmbeddingDim()),
      LEGAL_RERANK_PROVIDER: "openrouter",
      LEGAL_RERANK_MODEL: merged.LEGAL_RERANK_MODEL || defaultFreeOpenRouterRerankModel(),
      OPENROUTER_EMBEDDING_MODEL: merged.OPENROUTER_EMBEDDING_MODEL || defaultFreeOpenRouterEmbeddingModel(),
      OPENROUTER_RERANK_MODEL: merged.OPENROUTER_RERANK_MODEL || defaultFreeOpenRouterRerankModel(),
    };
  }
  return {
    ...PRODUCTION_OVERRIDES_BASE,
    LEGAL_EMBEDDING_PROVIDER: "local-hash",
    LEGAL_EMBEDDING_DIM: "384",
    LEGAL_RERANK_PROVIDER: "local",
  };
}

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return {};
  const env = {};
  for (const rawLine of fs.readFileSync(filePath, "utf8").split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#") || !line.includes("=")) continue;
    const [key, ...rest] = line.split("=");
    env[key.trim()] = rest.join("=").trim().replace(/^['"]|['"]$/g, "");
  }
  return env;
}

function serializeEnv(env) {
  const lines = [
    "# Generated by scripts/bootstrap_production_scale_env.js",
    "# Do not commit this file.",
    "",
  ];
  for (const key of Object.keys(env).sort()) {
    lines.push(`${key}=${env[key]}`);
  }
  lines.push("");
  return lines.join("\n");
}

function assignEnvFile(target, filePath, { skipEmpty = false, keysOnly = null } = {}) {
  if (!fs.existsSync(filePath)) return;
  const parsed = parseEnvFile(filePath);
  for (const [key, value] of Object.entries(parsed)) {
    if (keysOnly && !keysOnly.includes(key)) continue;
    if (skipEmpty && !value) continue;
    target[key] = value;
  }
}

function bootstrap({ targetPath = TARGET_ENV } = {}) {
  const merged = {};
  assignEnvFile(merged, EVIDENCE_ENV, { skipEmpty: true });
  assignEnvFile(merged, VERCEL_PRODUCTION_ENV, {
    skipEmpty: true,
    keysOnly: ["OPENROUTER_API_KEY", "SUPABASE_URL", "SUPABASE_SERVICE_ROLE_KEY"],
  });
  mergeRuntimeSecrets(merged);
  if (!merged.OPENROUTER_API_KEY) {
    throw new Error(
      "bootstrap_missing_openrouter_key: set OPENROUTER_API_KEY on Vercel Production, then run "
      + "`cd hk-criminal-procedure-graphrag-evidence && vercel env run -e production -- node ../hk-criminal-procedure-graphrag/scripts/bootstrap_production_scale_env.js`",
    );
  }
  Object.assign(merged, productionOverrides(merged));
  fs.writeFileSync(targetPath, serializeEnv(merged), { mode: 0o600 });
  return {
    target_path: targetPath,
    source_paths: [EVIDENCE_ENV, VERCEL_PRODUCTION_ENV],
    openrouter_key_suffix: String(merged.OPENROUTER_API_KEY).slice(-6),
    overrides: productionOverrides(merged),
    has_openrouter_key: Boolean(merged.OPENROUTER_API_KEY),
    has_qdrant_url: Boolean(merged.QDRANT_URL),
    has_supabase: Boolean(merged.SUPABASE_URL && merged.SUPABASE_SERVICE_ROLE_KEY),
  };
}

const SECRET_KEYS = [
  "OPENROUTER_API_KEY",
  "OPENAI_API_KEY",
  "VOYAGE_API_KEY",
  "COHERE_API_KEY",
  "SUPABASE_URL",
  "SUPABASE_SERVICE_ROLE_KEY",
  "SUPABASE_DB_URL",
  "QDRANT_URL",
  "QDRANT_API_KEY",
  "DEEPSEEK_API_KEY",
  "LEGAL_REVIEW_ADMIN_TOKEN",
  "INNGEST_EVENT_KEY",
  "INNGEST_SIGNING_KEY",
];

function mergeRuntimeSecrets(target) {
  for (const key of SECRET_KEYS) {
    if (process.env[key]) target[key] = process.env[key];
  }
  return target;
}

function runNode(script, extraArgs = [], env = process.env) {
  return spawnSync(process.execPath, [path.join(ROOT, "scripts", script), ...extraArgs], {
    cwd: ROOT,
    env,
    encoding: "utf8",
  });
}

function main() {
  const report = bootstrap();
  const env = { ...process.env, ...parseEnvFile(TARGET_ENV) };
  mergeRuntimeSecrets(env);
  const steps = [];

  steps.push({ step: "bootstrap_env", ...report });

  const readiness = runNode("validate_case_scale_readiness.js", ["--target-cases", "10000", "--require-green"], env);
  steps.push({
    step: "validate_10k_readiness",
    ok: readiness.status === 0,
    status: readiness.status,
    stdout: readiness.stdout,
    stderr: readiness.stderr,
  });
  if (readiness.status !== 0) {
    console.log(JSON.stringify({ status: "blocked_at_readiness", steps }, null, 2));
    process.exit(1);
  }

  const registry = runNode("build_case_scale_registry.js", ["--target-cases", "10000"], env);
  steps.push({
    step: "build_case_registry",
    ok: registry.status === 0,
    stdout: registry.stdout,
    stderr: registry.stderr,
  });

  const planPath = path.join(ROOT, "artifacts", "case_scale_10000.json");
  const plan = runNode("plan_case_scale_run.js", [
    "--target-cases", "10000",
    "--scope", "criminal_domain_public_cases",
    "--cases-per-shard", "100",
    "--output", planPath,
  ], env);
  steps.push({
    step: "plan_10k_run",
    ok: plan.status === 0,
    plan_path: planPath,
    stdout: plan.stdout,
    stderr: plan.stderr,
  });
  if (plan.status !== 0) {
    console.log(JSON.stringify({ status: "blocked_at_plan", steps }, null, 2));
    process.exit(1);
  }

  const planJson = JSON.parse(fs.readFileSync(planPath, "utf8"));
  if (!planJson.execution_allowed) {
    console.log(JSON.stringify({ status: "plan_not_execution_allowed", plan: planJson, steps }, null, 2));
    process.exit(1);
  }

  const shardGuard = runNode("run_case_scale_shard.js", [
    "--plan", planPath,
    "--shard-id", "shard_0001",
    "--dispatch",
    "--output", path.join(ROOT, "artifacts", "case_scale_shards", "shard_0001_guard.json"),
  ], env);
  steps.push({
    step: "dispatch_shard_0001",
    ok: shardGuard.status === 0,
    stdout: shardGuard.stdout,
    stderr: shardGuard.stderr,
  });

  const shardExec = runNode("execute_case_scale_shard.js", [
    "--plan", planPath,
    "--shard-id", "shard_0001",
    "--output", path.join(ROOT, "artifacts", "case_scale_shards", "shard_0001_execute.json"),
  ], env);
  steps.push({
    step: "execute_shard_0001",
    ok: shardExec.status === 0,
    stdout: shardExec.stdout,
    stderr: shardExec.stderr,
  });

  const finalStatus = steps.every(item => item.ok !== false) ? "green_10k_pipeline_bootstrapped" : "completed_with_failures";
  const summary = {
    status: finalStatus,
    target_cases: 10000,
    plan_path: planPath,
    registry_path: path.join(ROOT, "data", "legal_ingest", "criminal_evidence_tree_v1", "case_registry_public_v1.json"),
    prod_collections: {
      paragraphs: env.QDRANT_COLLECTION_PARAGRAPHS,
      propositions: env.QDRANT_COLLECTION_PROPOSITIONS,
    },
    steps,
  };
  fs.writeFileSync(path.join(ROOT, "artifacts", "case_scale_10000_summary.json"), `${JSON.stringify(summary, null, 2)}\n`);
  console.log(JSON.stringify(summary, null, 2));
  if (finalStatus !== "green_10k_pipeline_bootstrapped") process.exit(1);
}

try {
  main();
} catch (error) {
  console.error(JSON.stringify({ status: "bootstrap_failed", message: error.message }, null, 2));
  process.exit(1);
}
