const LAW_TREE_CONFIGS = [
  {
    tree_id: "criminal_law.theft.dishonesty",
    label: "Theft / dishonesty",
    broad_legal_topic: "Theft dishonesty, mistake and forgot-to-pay fact patterns",
    domain_id: "criminal_law_hk",
    issue_tags: [
      "criminal_law.theft.dishonesty",
      "criminal_law.dishonesty",
      "criminal_law.theft.mens_rea",
      "criminal_law.theft.mistake_or_forgot_to_pay",
    ],
    selection_issue_tags: ["criminal_law.theft.dishonesty", "criminal_law.dishonesty"],
    selection_doctrine_node_ids: ["criminal_law_hk.theft.dishonesty"],
    principle_terms: ["dishonesty", "dishonest", "mens rea", "mistake"],
    viewer_node_ids: ["crim_theft_dishonesty"],
    doctrine_node_ids: ["criminal_law_hk.theft.dishonesty", "criminal_law_hk.theft"],
    keywords: ["dishonesty", "dishonest", "mens rea", "forgot", "pay", "shoplifting", "mistake"],
    fact_pattern_query: "I picked up goods in a shop, forgot to pay, and left. What theft dishonesty issues matter?",
  },
  {
    tree_id: "criminal_law.theft.intention_permanently_deprive",
    label: "Intention permanently to deprive",
    broad_legal_topic: "Theft intention permanently to deprive and return-of-property arguments",
    domain_id: "criminal_law_hk",
    issue_tags: [
      "criminal_law.theft.intention_permanently_deprive",
      "criminal_law.theft.intent.deprive",
      "criminal_law.theft.mens_rea",
    ],
    selection_issue_tags: ["criminal_law.theft.intention_permanently_deprive", "criminal_law.theft.intent.deprive"],
    selection_doctrine_node_ids: ["criminal_law_hk.theft.intent.deprive"],
    principle_terms: ["intention permanently to deprive", "permanently deprive", "return the item"],
    viewer_node_ids: ["crim_theft_intent_deprive"],
    doctrine_node_ids: ["criminal_law_hk.theft.intent.deprive", "criminal_law_hk.theft"],
    keywords: ["permanently deprive", "intention", "return", "owner", "theft"],
    fact_pattern_query: "What does intention permanently to deprive mean if I planned to return the item?",
  },
  {
    tree_id: "criminal_law.theft.belonging_to_another",
    label: "Belonging to another",
    broad_legal_topic: "Theft property belonging to another, possession and ownership belief",
    domain_id: "criminal_law_hk",
    issue_tags: [
      "criminal_law.theft.belonging_to_another",
      "criminal_law.theft.property",
      "criminal_law.theft.appropriation",
    ],
    selection_issue_tags: ["criminal_law.theft.belonging_to_another"],
    selection_doctrine_node_ids: ["criminal_law_hk.theft.appropriation"],
    principle_terms: ["belonging to another", "property-belonging", "owner", "possession", "appropriation"],
    viewer_node_ids: ["crim_theft"],
    doctrine_node_ids: ["criminal_law_hk.theft", "criminal_law_hk.theft.appropriation"],
    keywords: ["belonging to another", "property", "possession", "owner", "appropriation"],
    fact_pattern_query: "The property was in someone else's possession, but I thought it was mine. What theft issue is this?",
  },
  {
    tree_id: "criminal_procedure.interview_caution_confession",
    label: "Interview, caution and confession",
    broad_legal_topic: "Police interview caution, right of silence, confession admissibility and residual discretion",
    domain_id: "criminal_procedure_hk",
    issue_tags: [
      "criminal_procedure.interview_caution",
      "criminal_procedure.confession",
      "criminal_procedure.right_of_silence",
      "criminal_procedure.undercover_confession",
    ],
    selection_issue_tags: [
      "criminal_procedure.interview_caution",
      "criminal_procedure.confession",
      "criminal_procedure.right_of_silence",
      "criminal_procedure.undercover_confession",
    ],
    selection_doctrine_node_ids: [
      "criminal_procedure_hk.hksar_v_lam_tat_ming",
      "criminal_procedure_hk.invest_arrest_without_warrant",
      "criminal_procedure_hk.invest_detention_after_arrest",
    ],
    principle_terms: ["interview", "caution", "confession", "right of silence", "admission", "undercover"],
    viewer_node_ids: ["hksar_v_lam_tat_ming", "invest_arrest_without_warrant", "invest_detention_after_arrest"],
    doctrine_node_ids: [
      "criminal_procedure_hk.hksar_v_lam_tat_ming",
      "criminal_procedure_hk.invest_arrest_without_warrant",
      "criminal_procedure_hk.invest_detention_after_arrest",
    ],
    keywords: ["interview", "caution", "right of silence", "confession", "admission", "undercover"],
    fact_pattern_query: "The police interviewed me without explaining my rights. What issues matter?",
  },
  {
    tree_id: "criminal_procedure.bail",
    label: "Bail",
    broad_legal_topic: "Bail factors, remand, surrender and procedure after theft/dishonesty arrest",
    domain_id: "criminal_procedure_hk",
    issue_tags: ["criminal_procedure.bail"],
    selection_issue_tags: ["criminal_procedure.bail", "criminal_evidence.bail"],
    selection_doctrine_node_ids: ["criminal_procedure_hk.bail", "criminal_procedure_hk.bail_factors", "criminal_procedure_hk.bail_right_to_bail", "criminal_procedure_hk.nsl_bail"],
    principle_terms: ["bail", "remand", "custody", "surrender", "surety"],
    viewer_node_ids: ["bail_factors", "bail_right_to_bail", "bail_pending_appeal"],
    doctrine_node_ids: ["criminal_procedure_hk.bail", "criminal_procedure_hk.bail_factors", "criminal_procedure_hk.bail_right_to_bail"],
    flow_step_ids: ["bail_flow_step3", "bail_flow_step4", "bail_flow_step5"],
    keywords: ["bail", "remand", "custody", "recognizance", "surety", "surrender"],
    fact_pattern_query: "What bail factors matter after a theft arrest?",
  },
  {
    tree_id: "criminal_public_order.assembly_proportionality",
    label: "Public assembly and proportionality",
    broad_legal_topic: "Peaceful assembly restrictions, public order offences, proportionality and overcharging boundaries",
    domain_id: "criminal_law_hk",
    issue_tags: [
      "criminal_law.public_order",
      "constitutional_law.peaceful_assembly",
      "criminal_law.public_order.rights_overcharging",
      "criminal_law.public_order.unlawful_assembly",
      "criminal_law.public_order.joint_enterprise_accessory",
    ],
    selection_issue_tags: [
      "criminal_law.public_order",
      "constitutional_law.peaceful_assembly",
      "criminal_law.public_order.rights_overcharging",
      "criminal_law.public_order.unlawful_assembly",
      "criminal_law.public_order.joint_enterprise_accessory",
    ],
    selection_doctrine_node_ids: [
      "criminal_law_hk.public_order.rights_overcharging",
      "criminal_law_hk.public_order.unlawful_assembly",
      "criminal_law_hk.public_order.riot",
      "criminal_law_hk.public_order.presence_scene",
      "criminal_law_hk.public_order.joint_enterprise_accessory",
      "criminal_law_hk.secondary.liability",
      "criminal_law_hk.joint.enterprise",
      "criminal_procedure_hk.hksar_v_leung_kwok_hung",
    ],
    principle_terms: ["public order", "assembly", "proportionality", "unlawful assembly", "riot", "joint enterprise", "overcharging"],
    viewer_node_ids: ["public_order_rights_overcharging", "public_order_unlawful_assembly", "public_order_joint_enterprise_accessory"],
    doctrine_node_ids: [
      "criminal_law_hk.public_order.rights_overcharging",
      "criminal_law_hk.public_order.unlawful_assembly",
      "criminal_law_hk.public_order.joint_enterprise_accessory",
      "criminal_procedure_hk.hksar_v_leung_kwok_hung",
    ],
    keywords: ["public order", "assembly", "peaceful assembly", "proportionality", "restriction", "unlawful assembly", "riot", "overcharging"],
    fact_pattern_query: "I joined a peaceful protest and police restricted the route. What legal issues matter?",
  },
];

module.exports = {
  LAW_TREE_CONFIGS,
};
